### ISSUE TITLE
Predicted CHGCAR for VASP

### ISSUE THREAD

**Issue by vsumaria** [AIforGreatGood/charge3net#1]
I am trying to use the predicted Charge3Net CHGCAR to perform VASP calculation. I have one issue, the CHGCAR should contain both the charge density and the PAW one-center occupancies to be able to successfully read with ICHARG=1. Since charge3net only predicts the charge density, how do you circumvent this issue? 

I see the following error when running VASP:
RD_RHO_PAW: ion           1 data corrupt
WARNING: PAW occupancies are missing on CHGCAR

And end up not seeing as much speed up as you see in the paper.

**Comment by teddykoker** [comment]
Hi @vsumaria,

Thanks for the issue! In our work we use the ground truth augmentation occupancies for our calculations. They should be able to be computed from the charge density through self-consistent field steps; however we have not explored this direction much in this work.

**Comment by vaidishs** [comment]
So the FigureA.5 in the paper, is generated by getting the charge densities from Charge3net, combining them with augmented occupancies, and running a VASP calculation with this new "predicted" CHGCAR? 

If so, did you have any convergence issues? Did you have to use some density mixing?

**Comment by tawe141** [comment]
Hi @vaidishs,

Correct. I don't think we put this in the paper, but we observed a slightly higher proportion of calculations converge with ChargE3Net initialized calculations. All calculations used Materials Project defaults as detailed in [pymatgen](https://pymatgen.org/pymatgen.io.vasp.html#pymatgen.io.vasp.sets.MPStaticSet), which uses the default VASP parameters for density mixing.
