### ISSUE TITLE
return: MPRester' object has no attribute 'charge_density'

### ISSUE THREAD

**Issue by kk154** [AIforGreatGood/charge3net#2]
when i use :
python download/download_materials_project.py \
	--out_path ./data/mp_raw \
	--workers WORKERS \
	--task_id_file ./data/mpid_to_task_id_map.json \
	--mpi_api_key <"Your MP API Key">，
return: MPRester' object has no attribute 'charge_density'

**Comment by kk154** [comment]
ruturn:
Retrieving TaskDoc documents: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 60787.01it/s]
'MPRester' object has no attribute 'charge_density'
and I don't have the CHGCAR

**Comment by teddykoker** [comment]
cc @keeganq 

Hi @kk154,

It appears the Materials Project API made some changes to their interface and underlying API that make it no longer accessible to get charge densities from task IDs. I have opened an issue about this [here](https://github.com/materialsproject/api/issues/924). I have also pushed a quick fix to the `mp-download-fix` branch; you can run with `git pull && git checkout mp-download-fix`, then try running the download script again.

**Comment by kk154** [comment]
thanks
