### ISSUE TITLE
mpi-api version issue

### ISSUE THREAD

**Issue by arupmondal835** [AIforGreatGood/charge3net#7]
Hello, 

I have been trying to use the download code with most recent mp-api (0.42) but it is giving some attribute error such as 'MPRester' object has no attribute 'charge_density'.

```
(/home/amondal2/.conda-envs/charge3net) [amondal2@kd2 charge3net2] GPU $ python download/download_materials_project.py --out_path ./data/mp_raw --workers 1 --task_id_file ./data/mpid_to_task_id_map2.json --mp_api_key FVcwz7cJqSOVUMBCCDaCzlr4HMNQr5Ms
Gathering material ids and task ids from existing file
Starting API call with a single worker. Add additional workers with --workers
/kfs2/projects/gt47/amondal2/charge3net2/download/download_materials_project.py:56: DeprecationWarning: Accessing tasks data through MPRester.tasks is deprecated. Please use MPRester.materials.tasks instead.
  task_doc = mpr.tasks.get_data_by_id(task_id)
/kfs2/projects/gt47/amondal2/charge3net2/download/download_materials_project.py:56: DeprecationWarning: get_data_by_id is deprecated and will be removed soon. Please use the search method instead.
  task_doc = mpr.tasks.get_data_by_id(task_id)
Retrieving TaskDoc documents: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47127.01it/s]
'MPRester' object has no attribute 'charge_density'
Script Completed.
```

Then I downgraded it to 0.39 version as that version has charge_density attribute, but it can not locate the task ID i think and give the following prints without downloading any file.

```
(/home/amondal2/.conda-envs/charge3net) [amondal2@kd2 charge3net2] GPU $ python download/download_materials_project.py --out_path ./data/mp_raw --workers 1 --task_id_file ./data/mpid_to_task_id_map2.json --mp_api_key FVcwz7cJqSOVUMBCCDaCzlr4HMNQr5Ms
Gathering material ids and task ids from existing file
Starting API call with a single worker. Add additional workers with --workers
Accessing tasks data through MPRester.tasks is deprecated. Please use MPRester.materials.tasks instead.
No result for record mp-1439955.
No result for record mp-1793543.
No result for record mp-2292786.
Script Completed.
```

I think this is a versionr mp-api related issue. Could you take a look at it?

Thank you,
Arup

**Comment by teddykoker** [comment]
Hi Arup, thank you for the issue. Please see #2. We have introduced a fix on the `mp_download_fix` branch. Please let me know if you continue to run into any difficulties.

**Comment by arupmondal835** [comment]
Thanks, Teddy, this works (partially). I tried downloading the first three mpids: mp1, mp2, mp3. mp2 and mp3 can download the chgcar, but not the mp1. Even though the corresponding task ID is valid (I am using the same as this repo), it can not find the associated chgcar file and gives the following error:

unable to access bucket: 'materialsproject-parsed' key: 'chgcars/mp-1439955.json.gz' version: None error: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.

Did you encounter the same? Is this expected for some of the mpIDs? 

Thank you!

**Comment by teddykoker** [comment]
Last I checked they were in the process of [copying the data over to the new API](https://github.com/materialsproject/api/issues/924#issuecomment-2329837586), and it doesn't seem they have managed to copy all of the mpids that we originally used. It might be worth following up over there to see how the old charge densities could be obtained. In the mean time you should be able to download the most recent charge density associated with each mpid, with the caveat that it might not be identical to the original data we downloaded. Unfortunately I no longer have access to the original data we had downloaded, and I am unsure if my collaborators would be able release this data.

**Comment by arupmondal835** [comment]
Thanks, that is an informative thread. So what I understood is they have not copied the original task IDs used in this work, however, they have at least one or the most recent static task IDs for each mp ID. 

Do you know what the best way would be to get the most recent task IDs or the task IDs they have in the repo for each mpID? Also, given the changes in the new data, do you expect a lot of issues while training the model?

**Comment by teddykoker** [comment]
> Thanks, that is an informative thread. So what I understood is they have not copied the original task IDs used in this work, however, they have at least one or the most recent static task IDs for each mp ID.

Yes, that is my understanding.

> Do you know what the best way would be to get the most recent task IDs or the task IDs they have in the repo for each mpID? 

I think you should be able to use the `download_materials_project.py` script and change [this line](https://github.com/AIforGreatGood/charge3net/blob/37227d1dc6e4329ee9edc8b6f90494947b0301eb/download/download_materials_project.py#L157) to be:

```python
# note changing _read_in_write_out_task to _read_in_write_out
pool.Pool(args.workers).starmap(_read_in_write_out, [(args.mp_api_key, mpid, args.out_path) for mpid in mpids])
```

which should then end up calling `mpr.get_charge_density_from_material_id`, returning the most recent calculation. If this does not work let me know and I can try to offer a better solution.

> Also, given the changes in the new data, do you expect a lot of issues while training the model?

Any changes to the charge densities in the new data are likely quite minimal, so I wouldn't expect much of an overall difference in model performance. That being said, the performance metrics we calculated in the paper might deviate by small amounts if the data is not identical.

**Comment by arupmondal835** [comment]
Thanks a lot, this solves all the issues regarding the download code. On a different note, on the download command, there is a small typo, it shows up as mpi_api_key instead of mp_api_key.

**Comment by teddykoker** [comment]
Great! I have added all these changes in #8. Please let me know if you run into any other issues.
